#!/bin/bash

if [ -z "$1" ]; then
  echo "No project name provided."
  exit 1
fi

deployment="$HOME/ZIDE/deployment/$1"
source="$HOME/ZIDE/$1"

if [ ! -d "$source" ] || [ ! -d "$deployment" ]; then
  echo "project $1 not exists"
  exit 1
fi

dependencies=$(find "$deployment" | grep .jar | sed 's\^\<classpathentry kind="lib" path="\' | sed 's\$\" />\')

cat <<EOF >"$source"/.classpath
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="tools/export/src"/>
	<classpathentry kind="src" path="mickeylite-master"/>
	<classpathentry kind="src" path="tools/data_conversion/src"/>
	<classpathentry excluding="export/src/|security/build.bat|data_conversion/src/" kind="src" path="tools"/>
	<classpathentry kind="src" path="source/service"/>
	<classpathentry excluding="com/manageengine/sdpod/dashboard/util/PieDataProperties.java|com/adventnet/servicedesk/software/form/SWListViewForm.java|com/manageengine/sdpod/servlet/OrgInvitation.java|com/manageengine/sdpod/servlet/SDPDataMigrationServlet.java|com/manageengine/sdpod/dashboard/util/AngularDataProperties.java|com/manageengine/sdpod/dashboard/util/ConstructFusionChart.java|com/adventnet/servicedesk/tasks/transformer/TasksCheckBoxTransformer.java|com/manageengine/sdpod/transformer/SDPODTransformer.java|com/adventnet/servicedesk/setup/action/ServiceCatalogListcontroller.java|com/adventnet/servicedesk/software/form/SoftwareHomeForm.java|com/manageengine/sdpod/udf/UDFDetail.java|com/manageengine/sdpod/dashboard/util/FusionChartUtil.java" kind="src" path="source/library"/>
	<classpathentry kind="src" path="resources/src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER">
		<attributes>
			<attribute name="module" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.USER_LIBRARY/request_perf_SDPLIVE"/>
	<classpathentry kind="con" path="org.eclipse.jst.j2ee.internal.web.container"/>
	<classpathentry kind="con" path="org.eclipse.jst.j2ee.internal.module.container"/>
	<classpathentry kind="output" path="bin"/>
  $dependencies
</classpath>
EOF
