#!/bin/bash

URL="http://zide/softwares/eclipse/eclipse_linux.zip"
INSTALL_DIR="$HOME/applications/eclipse"
DESKTOP_ENTRY="$HOME/.local/share/applications/eclipse.desktop"
ZIP_FILE="eclipse_linux.zip"

# Check for required commands
for cmd in curl unzip mkdir rm; do
	if ! command -v $cmd &>/dev/null; then
		echo "Error: $cmd is not installed."
		exit 1
	fi
done

# Downloading ZIDE
echo "Downloading ZIDE..."
if ! curl -O "$URL"; then
	echo "Error: Failed to download $URL"
	exit 1
fi

# Creating applications folder if not exists
echo "Creating applications directory..."
mkdir -p "$HOME/applications"

# Removing existing installation if it exists
if [ -d "$INSTALL_DIR" ]; then
	echo "Removing existing installation..."
	rm -rf "$INSTALL_DIR"
fi

# Unzipping
echo "Unzipping..."
if ! unzip -qq "$ZIP_FILE" -d "$HOME/applications"; then
	echo "Error: Failed to unzip $ZIP_FILE"
	exit 1
fi

# Creating or truncating desktop icon entry
echo "Updating desktop entry..."
cat <<EOF >"$DESKTOP_ENTRY"
[Desktop Entry]
Name=Eclipse ZIDE
Exec=$INSTALL_DIR/eclipse
Terminal=false
Icon=$INSTALL_DIR/icon.xpm
Type=Application
EOF

# Deleting the downloaded zip file
echo "Cleaning up..."
rm "$ZIP_FILE"

echo "ZIDE installed successfully"
