"$schema" = 'https://starship.rs/config-schema.json'


# format = """
# $username\
# $hostname\
# $directory\
# $fill\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $hg_branch\
# $c\
# $golang\
# $java\
# $kotlin\
# $gradle\
# $lua\
# $nodejs\
# $ocaml\
# $python\
# $rust\
# $zig\
# $custom\
# $sudo\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# $status\
# $os\
# $container\
# $shell\
# $character"""
